---
title: "Rpf phage"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Responses of dormant Mycobacterium smegmatis to recombinant KBS0714 Rpf

# Setup Work Environment
```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/Rpf-Phage/")

# Load packages
require("png")
require("grid")

# Small custom functions
sem <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
```

# Data
```{r}
# Load and subset data
data <- read.table("data/20180611_KBSRpf-Smegmatis.txt", sep = "\t", header = T)
data88.noRpf <- data[ which(data$Treat == 'Rpf-' & data$Time == '88'),]
data88.plusRpf <- data[ which(data$Treat == 'Rpf+' & data$Time == '88'),]
data.merge <- rbind(data88.noRpf,data88.plusRpf)

# Rpf data table
Rpf.mean <- aggregate(data.merge$OD ~ Treat, data.merge, mean)
Rpf.sem <- aggregate(data.merge$OD ~ Treat, data.merge, sem)
Rpf.95.LL <- aggregate(data.merge$OD ~ Treat, data.merge,
          FUN = function(x) t.test(x)$conf.int[1])
Rpf.95.UL <- aggregate(data.merge$OD ~ Treat, data.merge,
          FUN = function(x) t.test(x)$conf.int[2])
Rpf.table <- data.frame(Rpf.mean[1], Rpf.mean[2], Rpf.sem[2],
          Rpf.95.LL[2], Rpf.95.UL[2])
colnames(Rpf.table) <- c("Treat", "mean", "sem", "LCI", "UCI")
```

# Statistics
```{r}
Rpf.t.test <- t.test(data.merge$OD ~ data.merge$Treat)
```

# Figure
```{r}
png(filename="figures/20180611_KBSRpf-Smegmatis.png",
        width = 800, height = 800, res = 96*2)

par(mar = c(4, 5, 1, 1))   

noRpf <- plot(jitter(rep(1, length(data88.noRpf$OD)), amount = 0.1), data88.noRpf$OD, 
      ylim = c(0.2, 1), xlim = c(0.5, 2.5), pch = 21, col = "lightgrey", bg = "lightgrey", lwd = 2,
      cex = 1.7, yaxt = "n", xaxt = "n", cex.lab = 2, cex.axis = 1.5,
      las = 1, ylab = "", xlab = "")
      box(lwd = 2)

points(jitter(rep(2, length(data88.plusRpf$OD)), amount = 0.1), data88.plusRpf$OD, pch = 21, 
       bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)
       
points(1, mean(data88.noRpf$OD), pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5) 
points(2, mean(data88.plusRpf$OD), pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5)  

box(lwd = 2)

mtext(expression('Biomass (OD600)'), side = 2,
      outer = FALSE, cex = 1.5, line = 3.6, adj = 0.5)

# Major Axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.20", "0.40", "0.60", "0.80", "1.00"), at = c(0.2, 0.4, 0.6, 0.8, 1))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     at=c(0.2, 0.4, 0.6, 0.8, 1), labels = F, tck = -0.02)

axis(side = 1, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     labels = c("-Rpf", "+Rpf"), at = c(1, 2))

axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     at = c(1, 2), labels = F, tck = -0.02)

arrows(x0 = c(1,2), y0 = Rpf.table$mean, y1 = Rpf.table$LCI, angle = 90,
       length = 0.1, lwd = 2)
arrows(x0 = c(1,2), y0 = Rpf.table$mean, y1 = Rpf.table$UCI, angle = 90,
       length=0.1, lwd = 2)
       # Close Plot Device

mtext(expression(~italic("P")~"= 0.0003"), line = -15, cex = 1.2, at = 2.1)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("figures/20180611_KBSRpf-Smegmatis.png")
grid.raster(img)
```
     
     